### ISSUE TITLE
entity_embeddings.tsv

### ISSUE THREAD

**Issue by codeM78** [xyjigsaw/AcaFinder#3]
您好，entity_embeddings.tsv文件可以提供一下发送到邮箱xm_zhang@gs.zzu.edu.cn，或者文件格式可以告知一下吗。谢谢您

**Comment by xyjigsaw** [comment]
这个可以用pytorch-biggraph生成，参考这个[repo](https://github.com/xyjigsaw/Aminer2KG)

**Comment by codeM78** [comment]
好的，非常感谢您的帮助
